ORIGINAL_RESOLUTION = (1920, 1080)
WIDTH, HEIGHT = ORIGINAL_RESOLUTION

MONITOR_CONFIG = {"top": 0, "left": 0, "width": WIDTH, "height": HEIGHT}

RESCALED_WIDTH = int(WIDTH / 6)
RESCALED_HEIGHT = int(HEIGHT / 6)

INPUT_SHAPE = (3, RESCALED_HEIGHT, RESCALED_WIDTH)  # Add this line

NUM_ACTIONS = 10
